### PR TITLE
Setup pundit policies for group and user access.

### LINKED ISSUE #4: Implement Pundit Authorization
Implement authorization of documents and users with Pundit gem.

### PR DESCRIPTION
**Pull request by sanjayypatel**
Closes #4 
Users can only access and edit their own profiles.  Users can view their own organization info, but only moderators can edit the organization.

### CODE REVIEW

**Comment by sanjayypatel** [comment]
Steps for testing:
- Rerun seeds (I usually do a rake db:reset)
- Login as member@example.com, password 'helloworld'
- Should see Organization#show page with Edit Organization available.
- Hit Edit Organization and then search for member1 in sidebar
- Hit Invite for member1@example.com
- Sign Out
- Sign in as member1@example.com
- Should see user profile page with Notice to confirm invitation. Confirm invitation to join org
- Should stay on redirect to user profile, but this time without the notice and with a link to View Organization.
- View Organization - user can see information about organization, including list of members and roles, but cannot edit.

**Comment by bobbilee19** [comment]
all good except was stopped again because this user has no role yet.

**Comment by bobbilee19** [comment]
screen shot 2015-08-29 at 8 27 22 pm

**Comment by sanjayypatel** [comment]
Hmm, seems I forgot to make sure new users had a role set by default.  Working on a commit to fix this.

**Comment by sanjayypatel** [comment]
Closing and making further fixes in #28

**Pull request merged**
