### PR TITLE
Feature/user roles

### LINKED ISSUE #9: Implement user roles.
- Add role to User model.
- Roles will not affect authorization.

### PR DESCRIPTION
**Pull request by sanjayypatel**
Closes #9 
Added role to User model - user is either a manager or staff.

User roles do not affect authorization - they will be used to differentiate default views when logging into app.

Only moderator of an org can set user roles for members of that org.

### CODE REVIEW

**Comment by sanjayypatel** [comment]
Steps for testing:
- Sign In as member@example.com, password 'hello world'
- Should redirect to Organization page, hit Edit Organization
- Members of organization are to the right in sidebar.
- Change user's role from drop down menu and hit "Update"

**Comment by bobbilee19** [comment]
first thing first..

when i did step one, i got stopped here because my member did not have a role. so i set it in console to 'staff'

**Comment by bobbilee19** [comment]
step 2 good!

**Comment by bobbilee19** [comment]
screen shot 2015-08-29 at 8 18 38 pm

this isn't that clear to me. 

i would style this differently. lets talk about it. the drop down should be indented or something. would like to see what this looks like with a lot of users. 

2nd, side note, when i was trying to add more users to this org i  invited one and when u invite these users are they automatically added to the org? i think that they should have to accept before they are automatically added. from what i can tell, in console after i invite someone and run u.organizations the organization that just invited them is showing, even before the user has excepted?

**Comment by sanjayypatel** [comment]
Addressing Membership record creation in #28

**Pull request merged**
